services:
    db:
        image: postgres:17
        container_name: django_db
        restart: always
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: app
        ports:
            - "5532:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data

volumes:
    postgres_data: {}